AWSTemplateFormatVersion: "2010-09-09"

Transform: "AWS::Serverless-2016-10-31"

Description: An AWS Lambda application that calls the Lambda API.

Resources:
    Function:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            Runtime: nodejs14.x
            CodeUri: src
            Description: Call the AWS Lambda API
            Timeout: 10
            Policies:
                - AWSLambdaBasicExecutionRole
                - AWSLambda_ReadOnlyAccess
                - AWSXrayWriteOnlyAccess
            Tracing: Active
            Layers:
                - !Ref Dependencies

    Dependencies:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: Function-Layer
            Description: Dependencies for Lambda Function
            ContentUri: layer
            CompatibleRuntimes:
                - nodejs14.x