#!/bin/bash --norc

set -eo pipefail

declare DEFAULT="lambda-function-cfn-stack"

STACK="${1:-"${DEFAULT}"}"

echo "Deleting stack ${STACK}"

aws cloudformation delete-stack --stack-name "${STACK}" &>/dev/null || true
aws cloudformation wait stack-delete-complete --stack-name "${STACK}" &>/dev/null || true

if [ -f "bucket-name.artifact" ]; then
    ARTIFACT_BUCKET=$(cat "bucket-name.artifact")
    while true; do
        read -p "Delete deployment artifacts and bucket ($ARTIFACT_BUCKET)? (y/n)" response
        case $response in
            [Yy]* ) aws s3 rb --force s3://$ARTIFACT_BUCKET; rm bucket-name.txt; break;;
            [Nn]* ) break;;
            * ) echo "Response must start with y or n.";;
        esac
    done
fi

while true; do
    FUNCTION=$(aws cloudformation describe-stack-resource --stack-name "${STACK}" --logical-resource-id "Function" --query "StackResourceDetail.PhysicalResourceId" --output "text")

    read -p "Delete function log group (/aws/lambda/$FUNCTION)? (y/n)" response
    case $response in
        [Yy]* ) aws logs delete-log-group --log-group-name /aws/lambda/$FUNCTION; break;;
        [Nn]* ) break;;
        * ) echo "Response must start with y or n.";;
    esac
done

rm -f template.output.yaml
rm -rf layer package-lock.json
