#!/bin/bash --norc

set -eo pipefail

[[ -f "bucket-name.artifact" ]] || echo "[Error] No Bucket Artifacts Found"
[[ -f "bucket-name.artifact" ]] || exit 1

declare BUCKET="$(cat bucket-name.artifact)"

aws s3 rm "s3://${BUCKET}" --output "json"

if [[ "${?}" == "0" ]]; then
    echo "Successfully Removed Bucket" && echo

    echo "Cleaning Artifact(s) ..."

    rm -f bucket-name.artifact
    rm -f bucket-name.artifact.json

    echo " - Successful"
fi
