#!/bin/bash --norc

set -eo pipefail

declare TARGET="$(cat "bucket-name.artifact")"

[[ "${TARGET}" == "" ]] && echo "[Error] Bucket Artifact(s) Not Found"
[[ "${TARGET}" == "" ]] && exit 130

function package {
    [[ "${TARGET}" == "" ]] && echo "[Error] bucket-name.artifact not found"
    [[ "${TARGET}" == "" ]] && return 128

    aws cloudformation package --template-file "${1:-"template.yaml"}" \
        --output-template-file "${2:-"template.output.yaml"}"  \
            --s3-bucket "${3:-"${TARGET}"}"
}

function deploy {
    declare DEFAULT="lambda-function-cfn-stack"

    [[ "${TARGET}" == "" ]] && echo "[Error] template.output.yaml not found"
    [[ "${TARGET}" == "" ]] && return 129

    aws cloudformation deploy --stack-name "${1:-"${DEFAULT}"}" \
        --template-file "${2:-"template.output.yaml"}" \
            --capabilities CAPABILITY_NAMED_IAM

    echo "Successfully Established Stack" && echo
    echo "Awaiting Deployment ..." && aws cloudformation wait \
        stack-create-complete --stack-name "${1:-"${DEFAULT}"}"
}

echo "Packaging ..." && package
echo "Deploying ..." && deploy
echo "Complete"
