#!/bin/bash --norc

set -eo pipefail

function lambda {
    declare DEFAULT="lambda-function-cfn-stack"

    aws cloudformation describe-stack-resource --stack-name "${1:-"${DEFAULT}"}" \
        --query "StackResourceDetail.PhysicalResourceId" \
            --logical-resource-id "Function" \
                --output "text"
}

function invoke {
    aws lambda invoke --function-name "$(lambda)" \
        --cli-binary-format raw-in-base64-out \
              --payload "$(cat request.json)" \
                  response.json

    echo && cat response.json | jq -r "." && echo
}

invoke