#!/bin/bash --norc

set -eo pipefail

[[ -f "bucket-name.artifact" ]] && echo "[Error] Bucket Artifacts Found"
[[ -f "bucket-name.artifact" ]] && exit 1

function random () {
    printf "%s" "$(dd if=/dev/random bs=24 count=1 2>/dev/null | od -An -tx1 | tr -d " \t\n")"
}

declare BUCKET="$(random)"

printf "%s" "${BUCKET}" > "bucket-name.artifact"

echo "{ \"Bucket-Name\": \"${BUCKET}\" }" > "bucket-name.artifact.json"

aws s3 mb "s3://${BUCKET}" --output "json"
